### ISSUE TITLE
贪心鬼的 bug

### ISSUE THREAD

**Issue by ZJsheep** [OrangeX4/Reversi-Back#1]
![image](https://user-images.githubusercontent.com/73184640/122659852-7a38f580-d1ae-11eb-894e-ce735f22121a.png)
如图，此时应该是贪心鬼下棋，然而贪心鬼似乎陷入了迷茫。。。
（也许是服务器卡了？

**Comment by OrangeX4** [comment]
大概就是卡死了，只能刷新了，或者说自己目测一下（
